// speakersMeta.js
const speakersMeta = [
  {
    key: "aman",
    publicId: "aman_difyip",
    name: "Aman Dhattarwal",
    title: "Founder – Apni Kaksha",
    twitter: "https://x.com/amandhattarwal?lang=en",
    linkedin:
      "https://www.linkedin.com/in/dhattarwalaman/?originalSubdomain=in",
    instagram: "https://www.instagram.com/amandhattarwal/?hl=en",
  },
  {
    key: "amit",
    publicId: "amit_s3sffl",
    name: "Amit Chaudhary",
    title: "Founder – Lenskart",
    twitter: "",
    linkedin: "https://www.linkedin.com/in/4daxis/?originalSubdomain=in",
    instagram: "https://www.instagram.com/4daxis/?hl=en",
  },
  {
    key: "vijender",
    publicId: "vijender_izy2pb",
    name: "Dr. Vijender Chauhan",
    title: "Public Speaker",
    twitter: "https://x.com/masijeevi?lang=en",
    linkedin:
      "https://www.linkedin.com/in/vijendermasijeevi/?originalSubdomain=in",
    instagram: "https://www.instagram.com/masijeevi/?hl=en",
  },
  {
    key: "karan",
    publicId: "karan_exhgfa",
    name: "Karan Bajaj",
    title: "Founder – WhiteHat Jr.",
    twitter: "",
    linkedin:
      "https://www.linkedin.com/in/karan-bajaj-8806191/?originalSubdomain=in",
    instagram: "https://www.instagram.com/realkaranbajaj/?hl=en",
  },
  {
    key: "ashutoshh",
    publicId: "ashutoshh_koemma",
    name: "Ashutosh Naik",
    title: "Chief Compliance Officer (CCO) at Groww",
    twitter: "",
    linkedin:
      "https://www.linkedin.com/in/ashutosh-naik-187a8b2a/?originalSubdomain=in",
    instagram: "",
  },
  {
    key: "ravi",
    publicId: "ravi_ah3ckf",
    name: "Ravi K Ranjan",
    title: "Ex Shark Tank",
    twitter: "",
    linkedin: "https://www.linkedin.com/in/itsraviranjan/?originalSubdomain=ae",
    instagram: "",
  },
  {
    key: "sairaj",
    publicId: "sairaj_pyvrqz",
    name: "Sairaj Dhond",
    title: "Co‑founder of Wakao Foods",
    twitter: "http://x.com/sairajdhond?lang=en",
    linkedin:
      "https://www.linkedin.com/in/sairajdhondfounderwakaofoods/?originalSubdomain=in",
    instagram: "https://www.instagram.com/sairajdhond/?hl=en",
  },
  {
    key: "upasana",
    publicId: "upasana_bth4tu",
    name: "Upasana Makati",
    title: "Founder of White Print",
    twitter: "https://x.com/upasana_m?lang=en",
    linkedin: "https://www.linkedin.com/in/upasanamakati/?originalSubdomain=in",
    instagram: "https://www.instagram.com/upasanamakati/?hl=en",
  },
  {
    key: "muskaan",
    publicId: "muskaan_ti89ed",
    name: "Muskaan Sancheti",
    title: "Co‑founder of The State Plate",
    twitter: "https://x.com/heyitsmushh",
    linkedin:
      "https://www.linkedin.com/in/muskaan-sancheti/?originalSubdomain=in",
    instagram: "https://www.instagram.com/heyitsmush/?hl=en",
  },
  {
    key: "pawan",
    publicId: "pawan_wa1fvb",
    name: "Pawan Kumar Rai",
    title: "Founder – Ditto Insurance",
    twitter: "https://x.com/prai2303?lang=en",
    linkedin:
      "https://www.linkedin.com/in/pawan-kumar-rai-2a437a61/?originalSubdomain=in",
    instagram: "https://www.instagram.com/pawanrai_/?hl=en",
  },
  {
    key: "rishabhjain",
    publicId: "Rishabh_Jain_eegoig",
    name: "Rishabh Jain",
    title: "Labour Law Advisor",
    twitter:
      "https://x.com/rishsamjain?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor",
    linkedin: "https://www.linkedin.com/in/rishsamjain/?originalSubdomain=in",
    instagram: "https://www.instagram.com/rishsamjain/?hl=en",
  },
  {
    key: "akshay",
    publicId: "akshay_to716y",
    name: "Akshay Makar",
    title: "Educator",
    twitter: "https://x.com/akshaymakar5?lang=en",
    linkedin: "https://www.linkedin.com/in/akshaymakar/?originalSubdomain=in",
    instagram: "",
  },
  {
    key: "ayush",
    publicId: "ayush_x3vvvr",
    name: "Ayush Jaiswal",
    title: "Founder – Pesto",
    twitter: "https://x.com/aayushjaiswal07?lang=en",
    linkedin: "https://www.linkedin.com/in/aayushjaiswal07/",
    instagram: "https://www.instagram.com/aayushjaiswal07/?hl=en",
  },
  {
    key: "vatsal",
    publicId: "vatsal_fdemqf",
    name: "Vatsal Kanakiya",
    title: "Founder – 100X.VC",
    twitter: "https://x.com/vazzupk",
    linkedin: "https://www.linkedin.com/in/vazzup/?originalSubdomain=in",
    instagram: "https://www.instagram.com/vatsalkanakiya/",
  },
  {
    key: "richa",
    publicId: "richa_lwgdli",
    name: "Richa Shrivastava",
    title: "Managing Partner – Maker's Asylum",
    twitter: "",
    linkedin: "https://www.linkedin.com/in/shrivastavaricha/",
    instagram: "https://www.instagram.com/richashrivastava/",
  },
  {
    key: "sreedhar",
    publicId: "sreedhar_bny5cu",
    name: "Sridhar Jeychandran",
    title: "Co‑founder – Crio.do",
    twitter: "",
    linkedin:
      "https://www.linkedin.com/in/sridher-jeyachandran/?originalSubdomain=in",
    instagram: "",
  },
  {
    key: "aditya",
    publicId: "aditya_pjd2tx",
    name: "Aditya Ranjan",
    title: "Journey of an IAS",
    twitter: "",
    linkedin:
      "https://www.linkedin.com/in/aditya-ranjan-79b7b81b/?originalSubdomain=in",
    instagram: "https://www.instagram.com/adityaias/?hl=en",
  },
  {
    key: "nidhi",
    publicId: "nidhi_yh91c9",
    name: "Nidhi Bhatia",
    title: "Business coach & influencer",
    twitter: "https://x.com/Bollybeatz",
    linkedin:
      "https://www.linkedin.com/in/nidhibanthiamehta/?originalSubdomain=in",
    instagram: "https://www.instagram.com/nidhibanthiamehta/?hl=en",
  },
];

export default speakersMeta;
